services:
    PhpQa\Task\Ant:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: ant}

    PhpQa\Task\Atoum:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: atoum}

    PhpQa\Task\Behat:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: behat}

    PhpQa\Task\Brunch:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: brunch}

    PhpQa\Task\CloverCoverage:
        arguments:
            - '@filesystem'
        tags:
            - {name: grumphp.task, task: clover_coverage, priority: -100}

    PhpQa\Task\Codeception:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: codeception}

    PhpQa\Task\Composer:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
            - '@grumphp.util.filesystem'
        tags:
            - {name: grumphp.task, task: composer}

    PhpQa\Task\ComposerNormalize:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: composer_normalize}

    PhpQa\Task\ComposerScript:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: composer_script}

    PhpQa\Task\ComposerRequireChecker:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: composer_require_checker}

    PhpQa\Task\Deptrac:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: deptrac}

    PhpQa\Task\DoctrineOrm:
        arguments:
          - '@process_builder'
          - '@formatter.raw_process'
        tags:
          - {name: grumphp.task, task: doctrine_orm}

    PhpQa\Task\Ecs:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: ecs}

    PhpQa\Task\Gherkin:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: gherkin}

    PhpQa\Task\Git\Blacklist:
        arguments:
            - '@process_builder'
            - '@formatter.git_blacklist'
            - '@grumphp.io'
        tags:
            - {name: grumphp.task, task: git_blacklist}

    PhpQa\Task\Git\CommitMessage:
        arguments:
            - '@PhpQa\Git\GitRepository'
        tags:
            - {name: grumphp.task, task: git_commit_message}

    PhpQa\Task\Git\BranchName:
        arguments:
            - '@PhpQa\Git\GitRepository'
        tags:
            - {name: grumphp.task, task: git_branch_name}

    PhpQa\Task\ESLint:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: eslint}

    PhpQa\Task\FileSize:
        tags:
            - {name: grumphp.task, task: file_size}

    PhpQa\Task\Grunt:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: grunt}

    PhpQa\Task\Gulp:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: gulp}

    PhpQa\Task\Infection:
        arguments:
          - '@process_builder'
          - '@formatter.raw_process'
        tags:
          - {name: grumphp.task, task: infection}

    PhpQa\Task\JsonLint:
        arguments:
            - '@linter.jsonlint'
        tags:
            - {name: grumphp.task, task: jsonlint}

    PhpQa\Task\Kahlan:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: kahlan}

    PhpQa\Task\Make:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: make}

    PhpQa\Task\NpmScript:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: npm_script}

    PhpQa\Task\Paratest:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: paratest}

    PhpQa\Task\Pest:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: pest}

    PhpQa\Task\Phan:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: phan}

    PhpQa\Task\Phing:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: phing}

    PhpQa\Task\Php7cc:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: php7cc}

    PhpQa\Task\PhpArkitect:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: phparkitect}

    PhpQa\Task\PhpCpd:
        arguments:
          - '@process_builder'
          - '@formatter.raw_process'
        tags:
          - {name: grumphp.task, task: phpcpd}

    PhpQa\Task\Phpcs:
        arguments:
          - '@process_builder'
          - '@formatter.phpcs'
        tags:
          - {name: grumphp.task, task: phpcs}

    PhpQa\Task\PhpCsFixer:
        arguments:
          - '@process_builder'
          - '@formatter.phpcsfixer'
        tags:
          - {name: grumphp.task, task: phpcsfixer}
          - {name: grumphp.task, task: phpcsfixer2, aliasFor: phpcsfixer} # for old times-sake

    PhpQa\Task\PhpLint:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: phplint}

    PhpQa\Task\PhpMd:
        arguments:
          - '@process_builder'
          - '@formatter.raw_process'
        tags:
          - {name: grumphp.task, task: phpmd}

    PhpQa\Task\PhpMnd:
        arguments:
          - '@process_builder'
          - '@formatter.raw_process'
        tags:
          - {name: grumphp.task, task: phpmnd}

    PhpQa\Task\PhpParser:
        arguments:
            - '@grumphp.parser.php.parser'
        tags:
          - {name: grumphp.task, task: phpparser}

    PhpQa\Task\Phpspec:
        arguments:
          - '@process_builder'
          - '@formatter.raw_process'
        tags:
          - {name: grumphp.task, task: phpspec}

    PhpQa\Task\PhpStan:
        arguments:
          - '@process_builder'
          - '@formatter.raw_process'
        tags:
          - {name: grumphp.task, task: phpstan}

    PhpQa\Task\Phpunit:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: phpunit}

    PhpQa\Task\PhpunitBridge:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: phpunitbridge}

    PhpQa\Task\PhpVersion:
        arguments:
            - '@grumphp.util.phpversion'
        tags:
            - {name: grumphp.task, task: phpversion}

    PhpQa\Task\Prettier:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: prettier}

    PhpQa\Task\Progpilot:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: progpilot}

    PhpQa\Task\Psalm:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: psalm}

    PhpQa\Task\Rector:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - { name: grumphp.task, task: rector }

    PhpQa\Task\Robo:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: robo}

    PhpQa\Task\SecurityChecker:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: securitychecker}

    PhpQa\Task\SecurityCheckerEnlightn:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: securitychecker_enlightn}

    PhpQa\Task\SecurityCheckerLocal:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: securitychecker_local}

    PhpQa\Task\SecurityCheckerRoave:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
            - '@grumphp.util.filesystem'
        tags:
            - {name: grumphp.task, task: securitychecker_roave}

    PhpQa\Task\SecurityCheckerSymfony:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: securitychecker_symfony}

    PhpQa\Task\Shell:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: shell}

    PhpQa\Task\Stylelint:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: stylelint}

    PhpQa\Task\Tester:
        class:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: tester}

    PhpQa\Task\TwigCs:
        arguments:
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, task: twigcs}

    PhpQa\Task\XmlLint:
        arguments:
            - '@linter.xmllint'
        tags:
            - {name: grumphp.task, task: xmllint}

    PhpQa\Task\YamlLint:
        arguments:
            - '@linter.yamllint'
        tags:
            - {name: grumphp.task, task: yamllint}
