services:
    grumphp.util.filesystem:
        class: PhpQa\Util\Filesystem
        public: true

    PhpQa\Util\Paths:
        public: true
        arguments:
            - '@grumphp.util.filesystem'
            - '@PhpQa\Configuration\GuessedPaths'

    grumphp.util.phpversion:
        class: PhpQa\Util\PhpVersion
        arguments:
            -
              '5.6': '2018-12-31 23:59:59'
              '7.0': '2018-12-03 23:59:59'
              '7.1': '2019-12-01 23:59:59'
              '7.2': '2020-11-30 23:59:59'
              '7.3': '2021-12-06 23:59:59'
              '7.4': '2022-11-28 23:59:59'
              '8.0': '2023-11-26 23:59:59'
              '8.1': '2024-11-25 23:59:59'
              '8.2': '2025-12-08 23:59:59'
